<?php

/**
 * @file
 * Contains parichay.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function parichay_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the parichay module.
    case 'help.page.parichay':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manage and digitalize parichay') . '</p>';
      return $output;

    default:
  }
}
